#!/bin/sh

do_update () {
	cd /tmp
	git clone https://github.com/hepteract/scripts.git
	rm scripts/README.md
	cp -r scripts/* /usr/local/bin
	rm -rf scripts
}

if [ "$(whoami)" != "root" ]; then
	echo "Root permissions required to install."
	exit 1
fi

if [ "$(cat /usr/local/bin/script-version-identfier)" = "$(curl https://raw.githubusercontent.com/hepteract/scripts/master/script-version-identfier 2>/dev/null)" ]; then
	echo "No updates required."
else
	echo "Fetching updates..."
	do_update
fi
